---
-- KConfig premake5.
-- Copyright (c) 2026 Robbe Beernaert
---

local main_menu = {}
main_menu.__index = main_menu
local InputHelper = require("/UI/input")
--- Constructor
-- @param title string (The main title of the KConfig session)
function main_menu.new(title)
    local self = setmetatable({}, main_menu)

    self.title = title or "Project Configuration"
    self.root = require("/types/menu_container").new(self.title)
    self.config_path = ".config" -- Default save file

    -- Global lookup table for quick access to any config by name
    self.registry = {}

    return self
end

--- Registers a config into the global lookup table
-- This allows you to find 'ENABLE_VULKAN' without walking the whole tree
-- @param config_obj table (config_definition instance)
function main_menu:register(config_obj)
    if config_obj and config_obj.name then
        self.registry[config_obj.name] = config_obj
    end
end

--- Saves the current state of all registered configs to a file
-- @return boolean, string
function main_menu:save()
    local f, err = io.open(self.config_path, "w")
    if not f then return false, err end

    f:write("# Generated by Premake5 KConfig\n")
    f:write("# " .. os.date() .. "\n\n")

    -- Iterate through registered symbols alphabetically
    local keys = {}
    for k in pairs(self.registry) do table.insert(keys, k) end
    table.sort(keys)

    for _, name in ipairs(keys) do
        local cfg = self.registry[name]
        f:write(cfg:serialize() .. "\n")
    end

    f:close()
    print("KConfig: Configuration saved to " .. self.config_path)
    return true
end

--- Loads values from an existing .config file into the objects
function main_menu:load_values()
    if not os.isfile(self.config_path) then return false end

    for line in io.lines(self.config_path) do
        -- Match Key=Value pairs (ignoring comments)
        local name, val = line:match("^([^#%s]+)=(.*)$")
        if name and self.registry[name] then
            local cfg = self.registry[name]
            -- Basic type conversion
            if cfg.datatype == "bool" then
                cfg.value = (val == "y")
            else
                cfg.value = val
            end
        end
    end
    return true
end

--- Starts the interactive session
-- @param renderer table (The view component)
function main_menu:run(renderer)
    local menu_stack = { self.root }
    local selected = 1
    local running = true

    local layout = InputHelper.detect_layout()
    local up_key = (layout == "AZERTY") and "w" or "z"
    local down_key = "s" -- Both use 's' for down usually
    local save_key = (layout == "AZERTY") and "q" or "a"   

    while running do
        local current_menu = menu_stack[#menu_stack]
        local items = current_menu.items
        
        -- 1. Get current terminal width
        -- Note: If this feels slow on Windows, call it every 5th frame or 
        -- only when a specific key is pressed.
        local width = InputHelper.get_width()
        local divider = string.rep("-", width)

        InputHelper.clear()

        -- 2. Build the frame with width awareness
        local lines = renderer:assemble(items, selected, width)

        local frame = {}
        -- Center the title or just use the width for the bar
        table.insert(frame, "=== " .. self.title .. " ===")
        table.insert(frame, "Path: " .. self:_get_path(menu_stack))
        table.insert(frame, divider)
        
        for _, l in ipairs(lines) do 
            table.insert(frame, l) 
        end
        
        table.insert(frame, divider)
        table.insert(frame, "(" .. up_key .. "/" .. down_key .. ") Nav  (Space/Enter) Toggle  (B) Back  (".. save_key ..") Save")
        table.insert(frame, "\27[J")

        io.write(table.concat(frame, "\n"))
        io.flush()

        -- 3. Input & Logic
        local input = InputHelper.get_char()
        
        -- We handle \r (Windows Enter) and \n (Unix Enter) and " " (Space)
        local is_up = (input == up_key or input == "up" or input == "\27[a")
        local is_down = (input == down_key or input == "down" or input == "\27[b")
        local is_action = (input == "\r" or input == "\n" or input == " " or input == "" or input == "right")
        if is_up then
            selected = math.max(1, selected - 1)
        elseif is_down then
            selected = math.min(#items, selected + 1)
        elseif input == "q" then
            running = false
        elseif input == "b" or input =="left" then
            if #menu_stack > 1 then
                table.remove(menu_stack)
                selected = 1
            end
        elseif is_action then
            local active_item = items[selected]
            if active_item then
                if active_item.is_menu then
                    table.insert(menu_stack, active_item)
                    selected = 1
                else
                    self:_handle_interaction(active_item, renderer)
                end
            end
        end
    end

    self:save()
end

--- Internal: Handles value toggling/input
function main_menu:_handle_interaction(item, renderer)
    if item.datatype == "bool" then
        item.value = not item.value
    else
        local width = InputHelper.get_width()
        InputHelper.full_clear()
        
        -- Center vertically (push down)
        for i = 1, 6 do print("") end 

        -- Prepare the content for the box
        local content = {
            "EDITING: " .. (item.name or "Value"),
            "------------------------------------------------------------", -- Internal divider
            "Current: " .. tostring(item.value or "(empty)"),
            "",
            "Enter New Value:",
            "" -- This is our typing row
        }

        -- Generate and print
        local box = renderer:centered_box(content, width)
        for _, line in ipairs(box) do 
            print(line) 
        end

        -- POSITION THE CURSOR
        -- Move up 2 lines (past bottom border + empty row)
        io.write("\27[2A") 
        local left_margin = math.floor((width - 60) / 2) + 2
        io.write("\27[" .. left_margin .. "C")
        
        io.write("> ")
        local val = io.read()
        
        if val and val ~= "" then 
            item.value = val 
        end
        
        InputHelper.full_clear()
    end
end

--- Internal: Helper for Breadcrumbs
function main_menu:_get_path(stack)
    local names = {}
    for _, m in ipairs(stack) do table.insert(names, m.title) end
    return table.concat(names, " > ")
end

return main_menu
