---
-- KConfig premake5.
-- Copyright (c) 2026 Robbe Beernaert
---

local main_menu = {}
main_menu.__index = main_menu
local InputHelper = require("/UI/input")
--- Constructor
-- @param title string (The main title of the KConfig session)
function main_menu.new(title)
    local self = setmetatable({}, main_menu)

    self.title = title or "Project Configuration"
    self.root = require("/types/menu_container").new(self.title)
    self.config_path = ".config" -- Default save file

    -- Global lookup table for quick access to any config by name
    self.registry = {}

    return self
end

--- Registers a config into the global lookup table
-- This allows you to find 'ENABLE_VULKAN' without walking the whole tree
-- @param config_obj table (config_definition instance)
function main_menu:register(config_obj)
    if config_obj and config_obj.name then
        self.registry[config_obj.name] = config_obj
    end
end

--- Saves the current state of all registered configs to a file
-- @return boolean, string
function main_menu:save()
    local f, err = io.open(self.config_path, "w")
    if not f then return false, err end

    f:write("# Generated by Premake5 KConfig\n")
    f:write("# " .. os.date() .. "\n\n")

    -- Iterate through registered symbols alphabetically
    local keys = {}
    for k in pairs(self.registry) do table.insert(keys, k) end
    table.sort(keys)

    for _, name in ipairs(keys) do
        local cfg = self.registry[name]
        f:write(cfg:serialize() .. "\n")
    end

    f:close()
    print("KConfig: Configuration saved to " .. self.config_path)
    return true
end

--- Loads values from an existing .config file into the objects
function main_menu:load_values()
    if not os.isfile(self.config_path) then return false end

    for line in io.lines(self.config_path) do
        -- Match Key=Value pairs (ignoring comments)
        local name, val = line:match("^([^#%s]+)=(.*)$")
        if name and self.registry[name] then
            local cfg = self.registry[name]
            -- Basic type conversion
            if cfg.datatype == "bool" then
                cfg.value = (val == "y")
            else
                cfg.value = val
            end
        end
    end
    return true
end

--- Starts the interactive session
-- @param renderer table (The view component)
function main_menu:run(renderer)
    local menu_stack = { self.root }
    local selected = 1
    local running = true

    local layout = InputHelper.detect_layout()
    local up_key = (layout == "AZERTY") and "w" or "z"
    local down_key = "s" -- Both use 's' for down usually
    local save_key = (layout == "AZERTY") and "q" or "a"

    while running do
        local current_menu = menu_stack[#menu_stack]
        local items = current_menu.items

        -- 1. Get current terminal width
        -- Note: If this feels slow on Windows, call it every 5th frame or
        -- only when a specific key is pressed.
        local width = InputHelper.get_width()
        local divider = string.rep("-", width)

        InputHelper.clear()

        -- 2. Build the frame with width awareness
        local lines = renderer:assemble(items, selected, width)

        local frame = {}
        -- Center the title or just use the width for the bar
        table.insert(frame, "=== " .. self.title .. " ===")
        table.insert(frame, "Path: " .. self:_get_path(menu_stack))
        table.insert(frame, divider)

        for _, l in ipairs(lines) do
            table.insert(frame, l)
        end

        table.insert(frame, divider)
        table.insert(frame, "\27[0m(" .. up_key .. "/" .. down_key .. ") Nav  (Space/Enter) Toggle  (B) Back  (" .. save_key .. ") Save")
        table.insert(frame, "\27[J")

        io.write(table.concat(frame, "\n"))
        io.flush()

        -- 3. Input & Logic
        local input = InputHelper.get_char()

        -- We handle \r (Windows Enter) and \n (Unix Enter) and " " (Space)
        local is_up = (input == up_key or input == "up" or input == "\27[a")
        local is_down = (input == down_key or input == "down" or input == "\27[b")
        local is_action = (input == "\r" or input == "\n" or input == " " or input == "" or input == "right")
        if is_up then
            selected = math.max(1, selected - 1)
        elseif is_down then
            selected = math.min(#items, selected + 1)
        elseif input == save_key then
            running = false
        elseif input == "b" or input == "left" then
            if #menu_stack > 1 then
                table.remove(menu_stack)
                selected = 1
            end
        elseif is_action then
            local active_item = items[selected]
            if active_item then
                if active_item.is_menu then
                    table.insert(menu_stack, active_item)
                    selected = 1
                else
                    self:_handle_interaction(active_item, renderer)
                end
            end
        end
    end
    InputHelper.full_clear()
    self:save()
end

--- Internal: Handles value toggling/input
function main_menu:_handle_interaction(item, renderer)
    local handlers = {
        bool   = self._handle_bool,
        enum   = self._handle_enum,
        string = self._handle_string,
        number = self._handle_number,
        int    = self._handle_number,
        path   = self._handle_string -- Paths use the same UI as strings
    }

    local handler = handlers[item.datatype]
    if handler then
        handler(self, item, renderer)
    else
        -- Fallback for unknown types
        self:_handle_string(item, renderer)
    end
end

function main_menu:_handle_bool(item)
    -- Bare metal: just flip it and let the next loop draw the change
    item.value = not item.value
end

function main_menu:_handle_enum(item, renderer)
    if not item.choices or #item.choices == 0 then return end

    local width = InputHelper.get_width()
    local selected = 1

    -- Find current index to pre-select it
    for i, choice in ipairs(item.choices) do
        if choice == item.value then
            selected = i
            break
        end
    end

    local choosing = true
    while choosing do
        InputHelper.clear()

        -- Build the list for the box
        local content = {
            " SELECT OPTION: " .. item.name,
            "------------------------------------------------------------",
            "" -- Spacer
        }

        for i, choice in ipairs(item.choices) do
            local cursor = (i == selected) and " > " or "   "
            local mark   = (choice == item.value) and "[*]" or "[ ]"
            table.insert(content, string.format("%s %s %s", cursor, mark, choice))
        end

        table.insert(content, "") -- Spacer
        table.insert(content, " (Z/S) Move  (Enter) Select  (B/Esc) Cancel")

        -- Render the box
        for i = 1, 4 do print("") end -- Vertical center
        local box = renderer:centered_box(content, width)
        for _, line in ipairs(box) do print(line) end

        -- Handle Input (Directly using InputHelper)
        local char = InputHelper.get_char()

        -- Use the same logic as your main loop
        if char == "z" or char == "up" then
            selected = math.max(1, selected - 1)
        elseif char == "s" or char == "down" then
            selected = math.min(#item.choices, selected + 1)
        elseif char == "\r" or char == "\n" or char == " " or char == "" then
            item.value = item.choices[selected]
            choosing = false
        elseif char == "b" or char == "esc" or char == "left" then
            choosing = false
        end
    end

    InputHelper.full_clear()
end

function main_menu:_handle_string(item, renderer)
    local width = InputHelper.get_width()
    InputHelper.full_clear()

    -- Vertical padding
    for i = 1, 6 do print("") end

    local content = {
        " EDITING STRING: " .. item.name,
        " +----------------------------------------------------------+",
        " Current: " .. tostring(item.value or ""),
        " ",
        " Enter New Value:",
        " " -- Typing row
    }

    local box = renderer:centered_box(content, width)
    for _, line in ipairs(box) do print(line) end

    -- Position cursor 2 lines up and inside the box
    io.write("\27[2A\27[" .. (math.floor((width - 60) / 2) + 3) .. "C> ")

    local val = io.read()
    if val and val ~= "" then item.value = val end

    InputHelper.full_clear()
end

function main_menu:_handle_number(item, renderer)
    local width = InputHelper.get_width()
    InputHelper.full_clear()

    for i = 1, 6 do print("") end

    local content = {
        " EDITING NUMBER: " .. item.name,
        " +----------------------------------------------------------+",
        " Current: " .. tostring(item.value or 0),
        " ",
        " Enter Numeric Value:",
        " "
    }

    local box = renderer:centered_box(content, width)
    for _, line in ipairs(box) do print(line) end

    io.write("\27[2A\27[" .. (math.floor((width - 60) / 2) + 3) .. "C> ")

    local val = io.read()
    local num = tonumber(val)

    if num then
        item.value = num
    elseif val ~= "" then
        -- Optional: Add an error "flash" here if it's not a number
    end

    InputHelper.full_clear()
end

--- Internal: Helper for Breadcrumbs
function main_menu:_get_path(stack)
    local names = {}
    for _, m in ipairs(stack) do table.insert(names, m.title) end
    return table.concat(names, " > ")
end

return main_menu
