---
-- KConfig premake5.
-- Copyright (c) 2026 Robbe Beernaert
---

local main_menu = {}
main_menu.__index = main_menu

--- Constructor
-- @param title string (The main title of the KConfig session)
function main_menu.new(title)
    local self = setmetatable({}, main_menu)
    
    self.title = title or "Project Configuration"
    self.root = require("/types/menu_container").new(self.title)
    self.config_path = ".config" -- Default save file
    
    -- Global lookup table for quick access to any config by name
    self.registry = {} 
    
    return self
end

--- Registers a config into the global lookup table
-- This allows you to find 'ENABLE_VULKAN' without walking the whole tree
-- @param config_obj table (config_definition instance)
function main_menu:register(config_obj)
    if config_obj and config_obj.name then
        self.registry[config_obj.name] = config_obj
    end
end

--- Saves the current state of all registered configs to a file
-- @return boolean, string
function main_menu:save()
    local f, err = io.open(self.config_path, "w")
    if not f then return false, err end
    
    f:write("# Generated by Premake5 KConfig\n")
    f:write("# " .. os.date() .. "\n\n")
    
    -- Iterate through registered symbols alphabetically
    local keys = {}
    for k in pairs(self.registry) do table.insert(keys, k) end
    table.sort(keys)
    
    for _, name in ipairs(keys) do
        local cfg = self.registry[name]
        f:write(cfg:serialize() .. "\n")
    end
    
    f:close()
    print("KConfig: Configuration saved to " .. self.config_path)
    return true
end

--- Loads values from an existing .config file into the objects
function main_menu:load_values()
    if not os.isfile(self.config_path) then return false end
    
    for line in io.lines(self.config_path) do
        -- Match Key=Value pairs (ignoring comments)
        local name, val = line:match("^([^#%s]+)=(.*)$")
        if name and self.registry[name] then
            local cfg = self.registry[name]
            -- Basic type conversion
            if cfg.datatype == "bool" then
                cfg.value = (val == "y")
            else
                cfg.value = val
            end
        end
    end
    return true
end

return main_menu